/**
  Shell script generation for mixin operations.
*/
{
  lib,
  paths,
  git,
  validate,
}:
let
  inherit (builtins)
    attrNames
    attrValues
    concatStringsSep
    ;

  inherit (lib)
    concatMapStringsSep
    escapeShellArg
    mapAttrsToList
    ;

  inherit (paths) normalizePath detectPathConflicts;
  inherit (git)
    gitRemoteAdd
    gitFetch
    gitSubtreeAdd
    gitSubtreePull
    gitSubtreePush
    ;
  inherit (validate) validateMixins;

  /**
    Generate initialization script for all mixins.

    This sets up remotes and performs initial subtree adds.

    # Arguments

    - `mixins` (attrset): Map of mixin name -> mixin config

    # Returns

    Shell script string.
  */
  initScript =
    mixins:
    let
      validation = validateMixins mixins;
      conflicts = detectPathConflicts mixins;

      header = ''
        #!/usr/bin/env bash
        set -euo pipefail

        # Generated by imp.gitbits - Declarative repository composition
        # This script initializes all configured mixins

      '';

      perMixin =
        name: mixin:
        let
          mappingCmds = mapAttrsToList (
            src: dst:
            let
              prefix = normalizePath dst;
            in
            ''
              echo "  Adding ${src} -> ${dst}"
              ${gitSubtreeAdd name mixin prefix}
            ''
          ) mixin.mappings;
        in
        ''
          echo "Setting up mixin: ${name}"
          ${gitRemoteAdd name mixin.remote} 2>/dev/null || echo "  Remote already exists"
          ${gitFetch name mixin}
          ${concatStringsSep "\n" mappingCmds}
        '';

      body = concatStringsSep "\n" (mapAttrsToList perMixin mixins);
    in
    if !validation.valid then
      throw "Invalid mixin configuration:\n${concatStringsSep "\n" validation.errors}"
    else if conflicts != [ ] then
      throw "Path conflicts detected:\n${concatStringsSep "\n" conflicts}"
    else
      header + body;

  /**
    Generate pull script to sync all mixins from remotes.

    # Arguments

    - `mixins` (attrset): Map of mixin name -> mixin config

    # Returns

    Shell script string.
  */
  pullScript =
    mixins:
    let
      header = ''
        #!/usr/bin/env bash
        set -euo pipefail

        # Generated by imp.gitbits - Pull updates from all mixin remotes

      '';

      perMixin =
        name: mixin:
        let
          mappingCmds = mapAttrsToList (
            src: dst:
            let
              prefix = normalizePath dst;
            in
            ''
              echo "  Pulling ${dst}"
              ${gitSubtreePull name mixin prefix}
            ''
          ) mixin.mappings;
        in
        ''
          echo "Pulling mixin: ${name}"
          ${gitFetch name mixin}
          ${concatStringsSep "\n" mappingCmds}
        '';

      body = concatStringsSep "\n" (mapAttrsToList perMixin mixins);
    in
    header + body;

  /**
    Generate push script to sync changes back to mixin remotes.

    # Arguments

    - `mixins` (attrset): Map of mixin name -> mixin config

    # Returns

    Shell script string.
  */
  pushScript =
    mixins:
    let
      header = ''
        #!/usr/bin/env bash
        set -euo pipefail

        # Generated by imp.gitbits - Push changes to mixin remotes
        # WARNING: This pushes to upstream repos. Use with caution!

      '';

      perMixin =
        name: mixin:
        let
          mappingCmds = mapAttrsToList (
            src: dst:
            let
              prefix = normalizePath dst;
            in
            ''
              echo "  Pushing ${dst} -> ${name}:${src}"
              ${gitSubtreePush name mixin prefix}
            ''
          ) mixin.mappings;
        in
        ''
          echo "Pushing mixin: ${name}"
          ${concatStringsSep "\n" mappingCmds}
        '';

      body = concatStringsSep "\n" (mapAttrsToList perMixin mixins);
    in
    header + body;

  /**
    Generate status script to show mixin state.

    # Arguments

    - `mixins` (attrset): Map of mixin name -> mixin config

    # Returns

    Shell script string.
  */
  statusScript =
    mixins:
    let
      header = ''
        #!/usr/bin/env bash
        set -euo pipefail

        # Generated by imp.gitbits - Show mixin status

      '';

      perMixin =
        name: mixin:
        let
          branch = mixin.branch or "main";
          pathsList = concatStringsSep " " (
            map (d: escapeShellArg (normalizePath d)) (attrValues mixin.mappings)
          );
        in
        ''
          echo "Mixin: ${name}"
          echo "  Remote: ${mixin.remote}"
          echo "  Branch: ${branch}"
          echo "  Paths:"
          ${concatMapStringsSep "\n" (src: ''echo "    ${src} -> ${mixin.mappings.${src}}"'') (
            attrNames mixin.mappings
          )}
          echo "  Status:"
          git diff --stat HEAD -- ${pathsList} || true
          echo ""
        '';

      body = concatStringsSep "\n" (mapAttrsToList perMixin mixins);
    in
    header + body;

in
{
  inherit
    initScript
    pullScript
    pushScript
    statusScript
    ;
}
